config/routes.rb
Mybusiness::Application.routes.draw do
  

  resources :contests do
    resources :contestants
  end

  resources :video_listings

  devise_for :users, :path_names => { :sign_in => 'signin', :sign_out => 'signout', :sign_up => 'signup' }

  resources :news_posts

  get "pages/home"
  
  match "/video" => "pages#video"
  match "/wedding" => "pages#wedding"
  match "/wedding_contest_submit" => "pages#wedding_contest_submit"
  match "/news" => "news_posts#index"
  match "/contact" => "pages#contact"
  match "/signin" => redirect("/users/signin")

  match "/packages" => redirect("/")
  match "/addons" => redirect("/")
  match "/about" => redirect("/")
  match "/portfolio" => redirect("/")
  
  root :to => "pages#home"

end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  attr_accessible :email, :first_name, :last_name, :notes
  belongs_to :contest
  
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  
  before_filter :deny_access_for_non_admins, :except => [:create]
  before_filter :load_contest
  
  def index
    @contestants = @contest.contestants

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contestants }
    end
  end

  def show
    @contestant = @contest.contestants.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contestant }
    end
  end

  def new
    @contestant = @contest.contestants.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contestant }
    end
  end

  def edit
    @contestant = @contest.contestants.find(params[:id])
  end

  def create
    @contestant = @contest.contestants.build(params[:contest])

    respond_to do |format|
      if @contestant.save
        format.html { redirect_to @contest, notice: 'Contestant created.' }
        format.json { render json: @contest, status: :created, location: @contest }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @contestant = @contest.contestants.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @contest, notice: 'Contestant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contestant = @contest.contestants.find(params[:id])
    @contestant.destroy

    respond_to do |format|
      format.html { redirect_to @contest }
      format.json { head :no_content }
    end
  end
  
  private
    def load_contest
      @contest = Contest.find(params[:contest_id])
    end
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/views/contestants/_form.html.erb
<%= form_for(@contestant) do |f| %>
  <% if @contestant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contestant.errors.count, "error") %> prohibited this contestant from being saved:</h2>

      <ul>
      <% @contestant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_field :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contestants/edit.html.erb
<h1>Editing contestant</h1>

<%= render 'form' %>

<%= link_to 'Show', @contestant %> |
<%= link_to 'Back', contestants_path %>

app/views/contestants/index.html.erb
<h1>Listing contestants</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Email</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @contestants.each do |contestant| %>
  <tr>
    <td><%= contestant.first_name %></td>
    <td><%= contestant.last_name %></td>
    <td><%= contestant.email %></td>
    <td><%= contestant.notes %></td>
    <td><%= link_to 'Show', contestant %></td>
    <td><%= link_to 'Edit', edit_contestant_path(contestant) %></td>
    <td><%= link_to 'Destroy', contestant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contestant', new_contestant_path %>

app/views/contestants/new.html.erb
<h1>New contestant</h1>

<%= render 'form' %>

<%= link_to 'Back', contestants_path %>

app/views/contestants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @contestant.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @contestant.last_name %>
</p>

<p>
  <b>Email:</b>
  <%= @contestant.email %>
</p>

<p>
  <b>Notes:</b>
  <%= @contestant.notes %>
</p>


<%= link_to 'Edit', edit_contestant_path(@contestant) %> |
<%= link_to 'Back', contestants_path %>