config/routes.rb
Mybusiness::Application.routes.draw do
  

  resources :contests do
    resources :contestants
  end

  resources :video_listings

  devise_for :users, :path_names => { :sign_in => 'signin', :sign_out => 'signout', :sign_up => 'signup' }

  resources :news_posts

  get "pages/home"
  
  match "/video" => "pages#video"
  match "/wedding" => "pages#wedding"
  match "/wedding_contest_submit" => "pages#wedding_contest_submit"
  match "/news" => "news_posts#index"
  match "/contact" => "pages#contact"
  match "/signin" => redirect("/users/signin")

  match "/packages" => redirect("/")
  match "/addons" => redirect("/")
  match "/about" => redirect("/")
  match "/portfolio" => redirect("/")
  
  root :to => "pages#home"

end

app/models/video_listing.rb
class VideoListing < ActiveRecord::Base
  default_scope order("updated_at DESC")
  attr_accessible :image, :link, :name
  
  mount_uploader :image, ImageUploader
end

app/controllers/video_listings_controller.rb
class VideoListingsController < ApplicationController
  
  before_filter :deny_access_for_non_admins
  
  # GET /video_listings
  # GET /video_listings.json
  def index
    @video_listings = VideoListing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @video_listings }
    end
  end

  # GET /video_listings/1
  # GET /video_listings/1.json
  def show
    @video_listing = VideoListing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @video_listing }
    end
  end

  # GET /video_listings/new
  # GET /video_listings/new.json
  def new
    @video_listing = VideoListing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @video_listing }
    end
  end

  # GET /video_listings/1/edit
  def edit
    @video_listing = VideoListing.find(params[:id])
  end

  # POST /video_listings
  # POST /video_listings.json
  def create
    @video_listing = VideoListing.new(params[:video_listing])

    respond_to do |format|
      if @video_listing.save
        format.html { redirect_to "/video", notice: 'Video listing was successfully created.' }
        format.json { render json: @video_listing, status: :created, location: @video_listing }
      else
        format.html { render action: "new" }
        format.json { render json: @video_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /video_listings/1
  # PUT /video_listings/1.json
  def update
    @video_listing = VideoListing.find(params[:id])

    respond_to do |format|
      if @video_listing.update_attributes(params[:video_listing])
        format.html { redirect_to "/video", notice: 'Video listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @video_listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /video_listings/1
  # DELETE /video_listings/1.json
  def destroy
    @video_listing = VideoListing.find(params[:id])
    @video_listing.destroy

    respond_to do |format|
      format.html { redirect_to "/video" }
      format.json { head :no_content }
    end
  end
end

app/helpers/video_listings_helper.rb
module VideoListingsHelper
end

app/views/video_listings/_form.html.erb
<%= form_for(@video_listing, :html => {:multipart => true}) do |f| %>
  <% if @video_listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video_listing.errors.count, "error") %> prohibited this video_listing from being saved:</h2>

      <ul>
      <% @video_listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/video_listings/edit.html.erb
<div class="container">
	<h1>Editing Video Listing</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @video_listing %> |
	<%= link_to 'Back', "/video" %>	
</div>

app/views/video_listings/index.html.erb
<h1>Listing video_listings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Link</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @video_listings.each do |video_listing| %>
  <tr>
    <td><%= video_listing.name %></td>
    <td><%= video_listing.link %></td>
    <td><%= video_listing.image %></td>
    <td><%= link_to 'Show', video_listing %></td>
    <td><%= link_to 'Edit', edit_video_listing_path(video_listing) %></td>
    <td><%= link_to 'Destroy', video_listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Video listing', new_video_listing_path %>

app/views/video_listings/new.html.erb
<div class="container">
	<h1>New Video Listing</h1>

	<%= render 'form' %>

	<%= link_to 'Back', "/video" %>	
</div>

app/views/video_listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @video_listing.name %>
</p>

<p>
  <b>Link:</b>
  <%= @video_listing.link %>
</p>

<p>
  <b>Image:</b>
  <%= @video_listing.image %>
</p>


<%= link_to 'Edit', edit_video_listing_path(@video_listing) %> |
<%= link_to 'Back', video_listings_path %>