config/routes.rb
Mybusiness::Application.routes.draw do
  

  resources :contests do
    resources :contestants
  end

  resources :video_listings

  devise_for :users, :path_names => { :sign_in => 'signin', :sign_out => 'signout', :sign_up => 'signup' }

  resources :news_posts

  get "pages/home"
  
  match "/video" => "pages#video"
  match "/wedding" => "pages#wedding"
  match "/wedding_contest_submit" => "pages#wedding_contest_submit"
  match "/news" => "news_posts#index"
  match "/contact" => "pages#contact"
  match "/signin" => redirect("/users/signin")

  match "/packages" => redirect("/")
  match "/addons" => redirect("/")
  match "/about" => redirect("/")
  match "/portfolio" => redirect("/")
  
  root :to => "pages#home"

end

app/models/news_post.rb
class NewsPost < ActiveRecord::Base
  default_scope order("updated_at DESC")
  attr_accessible :body, :image, :title
  
  mount_uploader :image, ImageUploader
end

app/controllers/news_posts_controller.rb
class NewsPostsController < ApplicationController
  
  before_filter :deny_access_for_non_admins, :except => [:index, :show]
  
  # GET /news_posts
  # GET /news_posts.json
  def index
    @news_posts = NewsPost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news_posts }
    end
  end

  # GET /news_posts/1
  # GET /news_posts/1.json
  def show
    @news_post = NewsPost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news_post }
    end
  end

  # GET /news_posts/new
  # GET /news_posts/new.json
  def new
    @news_post = NewsPost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @news_post }
    end
  end

  # GET /news_posts/1/edit
  def edit
    @news_post = NewsPost.find(params[:id])
  end

  # POST /news_posts
  # POST /news_posts.json
  def create
    @news_post = NewsPost.new(params[:news_post])

    respond_to do |format|
      if @news_post.save
        format.html { redirect_to @news_post, notice: 'News post was successfully created.' }
        format.json { render json: @news_post, status: :created, location: @news_post }
      else
        format.html { render action: "new" }
        format.json { render json: @news_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /news_posts/1
  # PUT /news_posts/1.json
  def update
    @news_post = NewsPost.find(params[:id])

    respond_to do |format|
      if @news_post.update_attributes(params[:news_post])
        format.html { redirect_to @news_post, notice: 'News post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @news_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news_posts/1
  # DELETE /news_posts/1.json
  def destroy
    @news_post = NewsPost.find(params[:id])
    @news_post.destroy

    respond_to do |format|
      format.html { redirect_to news_posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/news_posts_helper.rb
module NewsPostsHelper
  def convert_time(timestamp)
    timestamp.in_time_zone(ActiveSupport::TimeZone.new("Eastern Time (US & Canada)"))
  end
  
  def convert_time_string(timestamp)
    convert_time(timestamp).strftime "%A, %B %d, %Y at %r"
  end
end

app/views/news_posts/_form.html.erb
<%= form_for(@news_post, :html => {:multipart => true}) do |f| %>
  <% if @news_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_post.errors.count, "error") %> prohibited this news_post from being saved:</h2>

      <ul>
      <% @news_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_posts/_news_post.html.erb
<div class="news-post">
	<div class="news-post-header">
		<div class="container">
			<%= news_post.title %>
			<% if admin? %>
				<div class="news-post-actions">
					<%= link_to "edit", edit_news_post_path(news_post) %>
					<%= link_to "delete", news_post, 
										:method => "delete", 
										:confirm => "Are you sure you want to delete this news post", 
										:delete => "Delete News Post?" %>
				</div>
			<% end %>
			<div class="news-post-date"><%= convert_time_string news_post.updated_at %></div>			
		</div>
	</div>
	<div class="news-post-body">
		<div class="container">
			<% if news_post.image_url.nil? %>
				<%= image_tag "defaultnews.png", :class => "news-post-image" %>
			<% else %>
				<%= image_tag news_post.image_url.to_s, :class => "news-post-image" %>
			<% end %>
			<%= raw news_post.body %><br>			
		</div>

		
	</div>
	<div class="clear-floats"></div>
</div>

app/views/news_posts/edit.html.erb
<<div class="container">
	<h1>Editing News Post</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @news_post %> |
	<%= link_to 'Back', news_posts_path %>	
</div>

app/views/news_posts/index.html.erb
<div class="news-navigation-bar">
	<div class="container">
		<div class="news-nav-links">
			<%= link_to "BACK TO BITESITE.CA", "/" %>
		</div>
		<div class="clear-floats"></div>
	</div>
</div>

<div class="news-index">
	<h1>News</h1>

	<% if admin? %>
		<div class="container">
			<%= link_to 'New News post', new_news_post_path %> <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
		</div>
	<% end %><br>
	
	<%= render @news_posts %>
</div>

app/views/news_posts/new.html.erb
<div class="container">
	<h1>New News Post</h1>

	<%= render 'form' %>

	<%= link_to 'Back', news_posts_path %>
	
</div>

app/views/news_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news_post.title %>
</p>

<p>
  <b>Body:</b>
  <%= @news_post.body %>
</p>

<p>
  <b>Image:</b>
  <%= @news_post.image %>
</p>


<%= link_to 'Edit', edit_news_post_path(@news_post) %> |
<%= link_to 'Back', news_posts_path %>